name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          # Enable Remote Desktop and disable Network Level Authentication (if needed)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force

          # Remove any existing rule with the same name to avoid duplication
          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          
          # For testing, allow any incoming connection on port 3389
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=3389

          # (Optional) Restart the Remote Desktop service to ensure changes take effect
          Restart-Service -Name TermService -Force

      - name: Create RDP User with Secure Password
        run: |
          Add-Type -AssemblyName System.Security
          $charSet = @{
              Upper   = [char[]](65..90)      # A-Z
              Lower   = [char[]](97..122)     # a-z
              Number  = [char[]](48..57)      # 0-9
              Special = ([char[]](33..47) + [char[]](58..64) +
                         [char[]](91..96) + [char[]](123..126)) # Special characters
          }
          $rawPassword = @()
          $rawPassword += $charSet.Upper | Get-Random -Count 4
          $rawPassword += $charSet.Lower | Get-Random -Count 4
          $rawPassword += $charSet.Number | Get-Random -Count 4
          $rawPassword += $charSet.Special | Get-Random -Count 4
          $password = -join ($rawPassword | Sort-Object { Get-Random })
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          
          echo "RDP_CREDS=User: RDP | Password: $password" >> $env:GITHUB_ENV
          
          if (-not (Get-LocalUser -Name "RDP")) {
              Write-Error "User creation failed"
              exit 1
          }

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Establish Tailscale Connection
        run: |
          # Bring up Tailscale with the provided auth key and set a unique hostname
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
          
          # Wait for Tailscale to assign an IP
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned. Exiting."
              exit 1
          }
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV


      - name: Install AnyDesk, set unattended password and print connection info
        shell: pwsh
        run: |
          # letöltés
          $url = "https://download.anydesk.com/AnyDesk.exe"
          $installer = "$env:TEMP\AnyDesk.exe"
          Write-Host "Downloading AnyDesk..."
          Invoke-WebRequest -Uri $url -OutFile $installer

          # telepítés silent
          Write-Host "Installing AnyDesk silently..."
          Start-Process -FilePath $installer -ArgumentList "/install","/silent","/norestart" -Wait
          Remove-Item $installer -Force -ErrorAction SilentlyContinue

          # keresés a telepített futtatható után
          $anydeskExe = Get-ChildItem -Path "C:\Program Files*","C:\Program Files (x86)*" -Filter "AnyDesk.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
          if ($anydeskExe) { $anydeskExe = $anydeskExe.FullName } else { 
            Write-Error "AnyDesk futtatható nem található a szokásos helyeken."
            exit 1
          }

          Write-Host "AnyDesk megtalálva: $anydeskExe"

          # jelszó a Secrets-ből
          if (-not $env:ANYDESK_PASSWORD) {
            Write-Error "ANYDESK_PASSWORD secret nincs beállítva!"
            exit 1
          }
          $pwd = $env:ANYDESK_PASSWORD

          # maszkolás a GitHub Actions logban (így nem jelenik meg nyíltan)
          Write-Host "::add-mask::$pwd"

          # set unattended password (pipe a jelszót)
          Write-Host "Beállítom az unattended jelszót..."
          cmd /c "echo $pwd | `"$anydeskExe`" --set-password" 2>$null

          Start-Sleep -Seconds 3

          # lekérjük az AnyDesk ID-t
          Write-Host "Lekérem az AnyDesk ID-t..."
          $id = & "$anydeskExe" --get-id 2>$null
          if (-not $id) {
            Write-Warning "Nem kaptunk ID-t a CLI-ből. Lehet GUI-only a verzió — ellenőrizd a runner asztalát."
            $id = "UNKNOWN"
          }
          $id = $id.Trim()

          # maszkoljuk az ID-t is a logokban
          if ($id -ne "UNKNOWN") { Write-Host "::add-mask::$id" }

          # mentsük env-be (felhasználhatod későbbi lépésekben)
          echo "ANYDESK_ID=$id" >> $env:GITHUB_ENV
          # nem írjuk ki a jelszót nyíltan — csak jelzés
          echo "ANYDESK_PASSWORD_SET=1" >> $env:GITHUB_ENV

          # olvasható összefoglaló (a tényleges jelszó NEM jelenik meg, mert maszkolva van)
          Write-Host ""
          Write-Host "=== ANYDESK HOZZÁFÉRÉS ==="
          Write-Host "ID: $id"
          Write-Host "Password: (a jelszó a repo secret: ANYDESK_PASSWORD) - a logban maszkolva."
          Write-Host "Tip: ha szeretnéd itt nyíltan látni a jelszót, add hozzá manuálisan a Write-Host ""Password: $pwd"" sort — de ez **nem biztonságos**!"
          Write-Host "==========================="



      
      - name: Verify RDP Accessibility
        run: |
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          
          # Test connectivity using Test-NetConnection against the Tailscale IP on port 3389
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "TCP connection to RDP port 3389 failed"
              exit 1
          }
          Write-Host "TCP connectivity successful!"

      - name: Maintain Connection
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: RDP"
          Write-Host "Password: $(echo $env:RDP_CREDS)"
          Write-Host "==================`n"
          
          # Keep runner active indefinitely (or until manually cancelled)
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
              Start-Sleep -Seconds 300
          }

